try:
    pass

# except:
#     pass      SyntaxError: default 'except:' must be last

except ValueError as err:
    pass

except NameError as err:
    pass

except FileNotFoundError as err:
    pass

except:
    pass